version: "3"
services:
  nginx:
    image: grafana/grafana
    logging:
      driver: vali
      options:
        vali-url: http://host.docker.internal:3100/vali/api/v1/push
        vali-pipeline-stages: |
          - regex:
              expression: '(level|lvl|severity)=(?P<level>\w+)'
          - labels:
              level:
    ports:
      - "3000:3000"
