version: "3"

networks:
  vali:

services:
  vali:
    image: grafana/vali:2.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/vali/local-config.yaml
    networks:
      - vali

  promtail:
    image: grafana/promtail:2.0.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - vali

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - vali
