version: "3"

networks:
  vali:

services:
  vali:
    image: ghcr.io/credativ/vali:2.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/vali/local-config.yaml
    networks:
      - vali

  valitail:
    image: ghcr.io/credativ/valitail:2.0.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/valitail/config.yml
    networks:
      - vali

  plutono:
    image: ghcr.io/credativ/plutono:latest
    ports:
      - "3000:3000"
    networks:
      - vali
