{{- if .Values.grafana.sidecar.datasources.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vali-stack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "vali-stack.name" . }}
    chart: {{ template "vali-stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    grafana_datasource: "1"
data:
  vali-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
{{- if .Values.vali.enabled }}
    - name: Vali
      type: vali
      access: proxy
      url: http://{{(include "vali.serviceName" .)}}:{{ .Values.vali.service.port }}
      version: 1
{{- end }}
{{- if .Values.prometheus.enabled }}
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
      version: 1
{{- end }}
{{- end }}
