grafana:
  enabled: true
  service:
    type: LoadBalancer
    port: 3000
  adminPassword: admin

prometheus:
  enabled: true
  pushgateway:
    enabled: false
  server:
    service:
      type: LoadBalancer
      servicePort: 9090

valitail:
  enabled: true
  image:
    pullPolicy: Never

fluent-bit:
  enable: false

vali:
  image:
    pullPolicy: Never
  service:
    type: LoadBalancer
