name: Unit tests

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15.3

      - name: Install package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make protobuf-compiler libsystemd-dev

      - name: Install Go dependencies
        run: |
          cd /tmp && GO111MODULE=on go get \
            github.com/golang/protobuf/protoc-gen-go@v1.3.0 \
            github.com/gogo/protobuf/protoc-gen-gogoslick@v1.2.1 \
            github.com/gogo/protobuf/gogoproto@v1.2.1

      - name: Test
        run: make BUILD_IN_CONTAINER=false test
